Repository metwork-framework/mfserv, pull requests merged in 2018-12, with the labels that each got.

#76 Add all MODULE-named environment varaiables into nginx.conf
  adm/__make_nginx_conf
  config/nginx.conf
Labels: Status: Review Needed, no-mergify

#78 Issue77
  adm/conf_monitor.sh
Labels: Status: Review Needed

#80 Remove a debug
  adm/conf_monitor.sh
Labels: Status: Closed

#82 [WIP] refactor: use new plugin_wrapper
  adm/_make_circus_conf
Labels: Merge Now, Status: Review Needed

#83 build: fix commit about nginx env
  adm/__make_nginx_conf
Labels: Merge Now, Status: Pending
