Repository metwork-framework/mfserv, pull requests merged in 2018-10, with the labels that each got.

#17 Update README.md
  README.md
Labels: Status: Review Needed, Type: To Categorize

#20 feat: better plugin crontab example
  adm/templates/plugins/default/{{cookiecutter.name}}/crontab
Labels: Status: Review Needed, Type: To Categorize

#22 feat: aiohttp upgrade
  layers/layer1_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, Type: Enhancement

#23 chore: createrepo package is now in build image
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#25 fix: better plugin routing
  config/nginx.conf
Labels: Status: Review Needed

#31 refactor: we use telegraf 1.7.1 for a long time now...
  config/telegraf.conf.custom
Labels: Status: Review Needed

#36 fix: fix lua lib paths
  adm/__make_nginx_conf
Labels: Status: Review Needed
