Repository metwork-framework/mfserv, pull requests merged in 2018-11, with the labels that each got.

#48 fix: fix timeout issues around conf_monitor restarts
  adm/conf_monitor.sh
Labels: Merge Now, Status: Review Needed

#51 feat: Add static plugin type and corresponding template
  adm/__make_nginx_conf
  adm/templates/plugins/static/cookiecutter.json
  adm/templates/plugins/static/hooks/post_gen_project.py
  adm/templates/plugins/static/{{cookiecutter.name}}/.layerapi2_dependencies
  adm/templates/plugins/static/{{cookiecutter.name}}/.layerapi2_label
  adm/templates/plugins/static/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/static/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/static/{{cookiecutter.name}}/main/index.html
  config/nginx.conf
Labels: Merge Now, Status: Review Needed

#57 build: add basic mfserv integration test
  integration_tests/0001_test_mfserv_operational/test_mfserv_operational.sh
Labels: Status: Review Needed

#58 add a custom README
  .metwork-framework/README.md
Labels: Merge Now, Status: Pending

#63 Update README.md
  .metwork-framework/README.md
Labels: Merge Now, Status: Pending

#66 refactor: refactor node plugin template
  adm/templates/plugins/node/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/node/{{cookiecutter.name}}/package.json
Labels: Status: Review Needed

#69 feat: add an internal welcome plugin
  Makefile
  config/config.ini
  config/nginx.conf
  plugins/Makefile
  plugins/welcome/.layerapi2_dependencies
  plugins/welcome/.layerapi2_label
  plugins/welcome/Makefile
  plugins/welcome/config.ini
  plugins/welcome/extra_general_nginx.conf
  plugins/welcome/main/cover.css
  plugins/welcome/main/css/bootstrap.min.css
  plugins/welcome/main/index.html
  plugins/welcome/main/js/bootstrap.min.js
  plugins/welcome/main/js/jquery-3.3.1.slim.min.js
Labels: Status: Review Needed

#70 feat: remove crontab support useless choice
  adm/templates/plugins/static/cookiecutter.json
Labels: Merge Now, Status: Review Needed

#71 fix: add missing file for node plugin template
  adm/templates/plugins/node/{{cookiecutter.name}}/node_package.json
Labels: Merge Now, Status: Review Needed

#73 fix: remove a warning in nginx logs
  config/nginx.conf
Labels: Status: Review Needed

#74 build: update .gitignore
  .gitignore
Labels: Merge Now, Status: Pending
