Repository metwork-framework/mfserv, pull requests merged in 2019-05, with the labels that each got.

#162 feat: remove double access-log messages with gunicorn
  adm/_make_circus_conf
Labels: Merge Now, Status: Review Needed

#164 fix: proxy_timeout was bypassed by gunicorn sync configurations
  adm/_make_circus_conf
Labels: Status: Review Needed, backport-to-0.6

#166 fix: proxy_timeout was bypassed by gunicorn sync configurations
  adm/_make_circus_conf
Labels: Merge Now, Status: Review Needed

#169 build: remove layer python
  layers/layer9_default/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_label
  layers/layer9_python/Makefile
Labels: Merge Now, Status: Review Needed

#170 docs: Update MFSERV documentation
  .gitignore
  bootstrap.sh
  doc/Makefile
  doc/_static/css/override_theme.css
  doc/_static/empty
  doc/_templates/breadcrumbs.html
  doc/_templates/layout.html
  doc/changelogs.rst
  doc/conf.py
  doc/images/logo-metwork.png
  doc/images/metwork.ico
  doc/index.rst
  doc/todo.rst
  layer_custom.md
  layers/layer1_nodejs/layer_custom.md
  layers/layer1_python2/layer_custom.md
  layers/layer1_python3/layer_custom.md
  layers/layer9_default/layer_custom.md
Labels: Status: Review Needed

#171 docs: fix invalid generated images link url
  doc/_images/logo-metwork.png
  doc/_images/metwork.ico
  doc/conf.py
Labels: Status: Review Needed

#172 build: fix gitignore
  .gitignore
Labels: Merge Now

#173 Misc
  adm/templates/plugins/_common/main/wsgi.py
  config/nginx.conf
Labels: Merge Now, Status: Revision Needed, backport-to-0.7

#180 build: fix extra_daemon feature and add a test
  adm/_make_circus_conf
  integration_tests/0011_extra_daemon/foo.sh
  integration_tests/0011_extra_daemon/test.py
Labels: Status: Review Needed, backport-to-0.7

#183 feat: use envtpl new option --reduce-multi-blank-lines
  adm/__make_nginx_conf
  adm/_make_circus_conf
  doc/Makefile
Labels: Merge Now, Status: Review Needed
