Repository metwork-framework/mfserv, pull requests merged in 2019-03, with the labels that each got.

#123 feat: nginx logs are now in JSON to prepare mfadmin#16
  adm/_make_nginx_conf
  config/config.ini
  config/nginx.conf
Labels: Status: Review Needed

#124 feat: add an option to send nginx access log to mfadmin
  config/circus.ini.custom
  config/config.ini
Labels: Status: Closed

#125 refactor: we prefer to keep an (empty) nodejs layer at mfserv level
  layers/layer1_nodejs/.layerapi2_dependencies
  layers/layer1_nodejs/.layerapi2_label
  layers/layer1_nodejs/Makefile
Labels: Merge Now

#126 fix: fix makefile target name
  adm/templates/plugins/nodets/{{cookiecutter.name}}/Makefile
Labels: Status: Review Needed

#130 feat: remove "name" from the list of questions during plugin bootstrap
  adm/templates/plugins/default/cookiecutter.json
  adm/templates/plugins/django/cookiecutter.json
  adm/templates/plugins/empty/cookiecutter.json
  adm/templates/plugins/node/cookiecutter.json
  adm/templates/plugins/nodets/cookiecutter.json
  adm/templates/plugins/static/cookiecutter.json
Labels: Status: Review Needed

#132 feat: remove plugins names from config.ini
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/django/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/empty/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/node/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/nodets/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/static/{{cookiecutter.name}}/config.ini
Labels: Status: Review Needed

#134 feat: add global nginx timeout configuration
  adm/__make_nginx_conf
  config/config.ini
  config/nginx.conf
Labels: Merge Now, Status: Review Needed
