Repository metwork-framework/mfserv, pull requests merged in 2019-07, with the labels that each got.

#208 feat: add proxy_ignore_client_abort option
  adm/bjoern_wrapper.py
  config/config.ini
  config/nginx.conf
Labels: Merge Now, Status: Review Needed, backport-to-0.7

#211 docs: Update MFSERV documentation
  .gitignore
  doc/_images/mfserv_debug_interactive.jpg
  doc/_images/mfserv_django_tuto_admin_site.jpg
  doc/_images/overall_architecture.svg
  doc/index.rst
  doc/mfserv_create_plugins.md
  doc/mfserv_debug_plugin.md
  doc/mfserv_deploy_plugin.md
  doc/mfserv_intro.md
  doc/mfserv_log.md
  doc/mfserv_miscellaneous.md
  doc/mfserv_quick_start.md
  doc/mfserv_tuning_monitoring.md
  doc/mfserv_tutorials.md
  doc/src/overall_architecture.graphml
  layers/layer1_nodejs/layer_custom.md
  layers/layer1_python2/layer_custom.md
  layers/layer1_python3/layer_custom.md
Labels: Status: Review Needed

#212 fix: issues in flask plugin.
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/templates/template_jinja_examples/index.html
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/templates/template_urlparse/index.html
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/wsgi.py
Labels: Status: Review Needed

#214 docs: Update MFSERV documentation
  doc/index.rst
  doc/mfserv_miscellaneous.md
Labels: Status: Review Needed

#216 fix: typo with virtualdomain based routing
  config/nginx.conf
Labels: Status: Revision Needed, backport-to-0.7

#219 fix: more precise condition to delete python-requirement
  adm/templates/plugins/_common/python2_virtualenv_sources.delete
  adm/templates/plugins/_common/python3_virtualenv_sources.delete
Labels: Status: Review Needed

#218 feat: plugins.hotswap feature!
  adm/Makefile
  adm/__make_nginx_conf
  adm/_make_circus_conf
  adm/mfxxx.start.custom
  adm/plugins.hotswap
  config/circus.ini.custom
  integration_tests/0020_hotswap/test.py
Labels: Status: Review Needed
