Repository metwork-framework/mfserv, pull requests merged in 2019-09, with the labels that each got.

#235 Nginx
  adm/__make_nginx_conf
  config/nginx.conf
Labels: Status: Review Needed, backport-to-0.8

#237 feat: replace MODULE* environment variables names by MFMODULE* (MODUL…
  Makefile
  adm/__make_nginx_conf
  adm/_check_circus_conf
  adm/_check_nginx_conf
  adm/_make_circus_conf
  adm/_make_nginx_conf
  adm/bjoern_wrapper.py
  adm/mfserv_conf_monitor.py
  adm/mfxxx.start.custom
  adm/plugins.hotswap
  adm/profile.custom
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/_common/crontab
  adm/templates/plugins/default/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/django/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/empty/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/flask/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/mediation/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/node/{{cookiecutter.name}}/.layerapi2_extra_env
  config/Makefile
  config/circus.ini.custom
  config/config.ini
  config/health.lua
  config/nginx.conf
  config/redis_plugin_xxx.conf
  doc/conf.py
  doc/mfserv_create_plugins.md
  doc/mfserv_deploy_plugin.md
  doc/mfserv_miscellaneous.md
  doc/mfserv_quick_start.md
  layers/layer1_python2/0500_extra_python_packages/Makefile.mk
  layers/layer1_python3/0500_extra_python_packages/Makefile.mk
  layers/layer1_python3/0700_aiohttp_metwork_middlewares/aiohttp_metwork_middlewares/__init__.py
  plugins/welcome/config.ini
Labels: Merge Now, Status: Revision Needed

#238 build: improve backward compatibility for MODULE_* => MFMODULE_*
  adm/__make_nginx_conf
Labels: Merge Now

#239 feat: add an option to configure the nginx real_ip feature
  config/config.ini
  config/nginx.conf
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#241 build: add components.md file
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#247 build: add some dir in gitignore
  .gitignore
Labels: Merge Now, Status: Review Needed

#246 feat: add nginx/server_tokens option in config
  config/config.ini
  config/nginx.conf
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#245 feat: load resty.core in nginx conf
  config/nginx.conf
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#250 build: fix utf8 char
  config/config.ini
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#253 fix: fix extra_nginx_server_conf_filename usage
  adm/__make_nginx_conf
Labels: Merge Now, Status: Review Needed
