Repository metwork-framework/mfserv, pull requests merged in 2019-11, with the labels that each got.

#274 Issue273
  adm/__make_nginx_conf
  adm/_plugins.is_dangerous
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/empty/{{cookiecutter.name}}/config.ini
  config/nginx.conf
Labels: Status: Review Needed, backport-to-0.9

#280 feat: improve empty plugin template and update documentation
  adm/templates/plugins/empty/cookiecutter.json
  adm/templates/plugins/empty/{{cookiecutter.name}}/bin/README
  doc/mfserv_create_plugins.md
  integration_tests/0011_extra_daemon/test.py
Labels: Status: Review Needed

#284 feat: adaptation to removal of layer misc@mfext
  .layerapi2_dependencies
  adm/Makefile
  adm/_plugins.postinstall
  adm/mfxxx.status.custom
  adm/templates/plugins/_common/Makefile
  adm/templates/plugins/flask/{{cookiecutter.name}}/Makefile
  bootstrap.sh
  config/Makefile
  plugins/welcome/Makefile
Labels: Merge Now, Status: Revision Needed
