Repository metwork-framework/mfserv, pull requests merged in 2019-08, with the labels that each got.

#221 template: keep the client session to prevent memory errors during mas…
  adm/templates/plugins/mediation/{{cookiecutter.name}}/main/application.py
Labels: Status: Review Needed

#222 build: synutil_lua => mfutil_lua migration
  config/stats.lua
Labels: Merge Now, Status: Review Needed

#223 feat: add plugin dir as valid path for lua files (for openresty)
  adm/__make_nginx_conf
Labels: Merge Now, Status: Review Needed

#226 build: little changes for the flask plugin
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/templates/template_jinja_examples/index.html
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/wsgi.py
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#225 build: use conf_monitor hooks
  config/circus.ini.custom
Labels: Merge Now, Status: Review Needed, backport-to-0.7, backport-to-0.8

#231 build: fix welcome plugin installation issue during the very first start
  adm/_make_nginx_conf
Labels: Merge Now, Status: Review Needed, backport-to-0.8
