Repository metwork-framework/mfserv, pull requests merged in 2019-04, with the labels that each got.

#137 feat: remove "name" from the list of questions during plugin bootstrap
  adm/templates/plugins/default/cookiecutter.json
  adm/templates/plugins/django/cookiecutter.json
  adm/templates/plugins/empty/cookiecutter.json
  adm/templates/plugins/node/cookiecutter.json
  adm/templates/plugins/static/cookiecutter.json
Labels: Status: Review Needed

#129 feat: split multiple node workers output to multiple files
  adm/_make_circus_conf
Labels: Status: Review Needed

#141 feat: send mflog logs to mfadmin
  config/config.ini
Labels: Merge Now, Status: Review Needed

#142 feat: add plugin name in logs
  config/nginx.conf
Labels: Merge Now, Status: Review Needed

#144 feat: add X-Request-Id header
  config/config.ini
  config/nginx.conf
Labels: Status: Review Needed

#145 Request id2
  .gitignore
  adm/mfserv_conf_monitor.py
  adm/templates/plugins/default/{{cookiecutter.name}}/main/application.py
  layers/layer1_python3/0700_aiohttp_metwork_middlewares/Makefile
  layers/layer1_python3/0700_aiohttp_metwork_middlewares/Makefile.mk
  layers/layer1_python3/0700_aiohttp_metwork_middlewares/aiohttp_metwork_middlewares/__init__.py
  layers/layer1_python3/0700_aiohttp_metwork_middlewares/setup.py
Labels: Status: Review Needed

#146 build: remove python prerequirement files (useless now)
  layers/layer1_python2/0500_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer1_python2/0500_extra_python_packages/prerequirements2.txt
  layers/layer1_python3/0500_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer1_python3/0500_extra_python_packages/prerequirements3.txt
Labels: Merge Now, Status: Revision Needed

#148 feat: add a mediation template
  adm/templates/plugins/mediation/cookiecutter.json
  adm/templates/plugins/mediation/hooks/post_gen_project.py
  adm/templates/plugins/mediation/{{cookiecutter.name}}/.layerapi2_dependencies
  adm/templates/plugins/mediation/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/mediation/{{cookiecutter.name}}/.layerapi2_label
  adm/templates/plugins/mediation/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/mediation/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/mediation/{{cookiecutter.name}}/crontab
  adm/templates/plugins/mediation/{{cookiecutter.name}}/main/__init__.py
  adm/templates/plugins/mediation/{{cookiecutter.name}}/main/application.py
  adm/templates/plugins/mediation/{{cookiecutter.name}}/python3_virtualenv_sources/requirements-to-freeze.txt
Labels: Merge Now, Status: Review Needed

#150 Typo
  .metwork-framework/plugins_guide.md
Labels: Status: Review Needed

#149 Typo on plugins_guide.md
  .metwork-framework/plugins_guide.md
Labels: Merge Now, Status: Review Needed

#152 fix: django template regression when bootstrapping
  adm/templates/plugins/django/cookiecutter.json
Labels: Merge Now, Status: Review Needed

#155 Plugindoc
  adm/templates/plugins/_common/config.ini
Labels: Merge Now, Status: Review Needed

#157 Nodefix2
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/django/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/mediation/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/node/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/nodets/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/static/{{cookiecutter.name}}/config.ini
Labels: Merge Now, Status: Review Needed

#158 build: move nginxfmt.py to mfcom
  adm/Makefile
  adm/nginxfmt.py
Labels: Merge Now, Status: Revision Needed

#159 build: fix mediation template after inheritance migration
  adm/templates/plugins/mediation/{{cookiecutter.name}}/config.ini
Labels: Merge Now
