Repository metwork-framework/mfserv, pull requests merged in 2019-01, with the labels that each got.

#85 build: exclude .plugin files in .gitignore
  .gitignore
Labels: Merge Now, Status: Pending

#86 build: add an integration test
  .gitignore
  integration_tests/0002_python3_plugin/_test.sh
  integration_tests/0002_python3_plugin/foobar/.layerapi2_dependencies
  integration_tests/0002_python3_plugin/foobar/.layerapi2_extra_env
  integration_tests/0002_python3_plugin/foobar/.layerapi2_label
  integration_tests/0002_python3_plugin/foobar/Makefile
  integration_tests/0002_python3_plugin/foobar/config.ini
  integration_tests/0002_python3_plugin/foobar/main/__init__.py
  integration_tests/0002_python3_plugin/foobar/main/wsgi.py
  integration_tests/0002_python3_plugin/foobar/python3_virtualenv_sources/requirements-to-freeze.txt
  integration_tests/0002_python3_plugin/foobar/python3_virtualenv_sources/requirements3.txt
  integration_tests/0002_python3_plugin/test.sh
Labels: Merge Now, Status: Pending, Status: Review Needed

#88 [WIP] build: use new mfcom plugin
  config/circus.ini.custom
Labels: Merge Now, Status: Pending, Status: Review Needed

#91 fix: fix the node plugin template
  adm/templates/plugins/node/{{cookiecutter.name}}/node_sources/package.json
Labels: Merge Now, Status: Pending

#92 build: remove a useless sleep and try to debug a CI problem
  integration_tests/0003_extra_daemons/_test.sh
Labels: Merge Now, Status: Review Needed

#95 Bettertests
  .gitignore
  integration_tests/0002_python3_plugin/_test.sh
  integration_tests/0002_python3_plugin/foobar/.autorestart_excludes
  integration_tests/0002_python3_plugin/foobar/.autorestart_includes
  integration_tests/0002_python3_plugin/foobar/config.ini
  integration_tests/0002_python3_plugin/foobar/main/wsgi.py
  integration_tests/0003_extra_daemons/foobar/toto
Labels: Merge Now, Status: Pending

#96 build: fix missing conf_monitor feature about crontab changes
  adm/conf_monitor.py
Labels: Merge Now, Status: Pending

#97 build: tmp removal of this test because of CI test issues
  integration_tests/0003_extra_daemons/_test.sh
  integration_tests/0003_extra_daemons/foobar/.autorestart_excludes
  integration_tests/0003_extra_daemons/foobar/.autorestart_includes
  integration_tests/0003_extra_daemons/foobar/.layerapi2_dependencies
  integration_tests/0003_extra_daemons/foobar/.layerapi2_extra_env
  integration_tests/0003_extra_daemons/foobar/.layerapi2_label
  integration_tests/0003_extra_daemons/foobar/Makefile
  integration_tests/0003_extra_daemons/foobar/bin/daemon.sh
  integration_tests/0003_extra_daemons/foobar/config.ini
  integration_tests/0003_extra_daemons/foobar/main/__init__.py
  integration_tests/0003_extra_daemons/foobar/main/wsgi.py
  integration_tests/0003_extra_daemons/foobar/python3_virtualenv_sources/requirements-to-freeze.txt
  integration_tests/0003_extra_daemons/foobar/python3_virtualenv_sources/requirements3.txt
  integration_tests/0003_extra_daemons/test.sh
Labels: Merge Now, Status: Pending

#98 [WIP] perf: increate stats sending delay
  config/nginx.conf
Labels: Merge Now, Status: Pending

#84 fix: fix some nginx location conflicts when used with multiple apps
  adm/__make_nginx_conf
  config/nginx.conf
Labels: Merge Now, Status: Review Needed

#103 fix: more reliable nginx reload in conf_monitor
  adm/conf_monitor.py
Labels: Status: Review Needed

#104 fix: upgrade django to version 2.1.5 to fix security vulnerability
  adm/templates/plugins/django/{{cookiecutter.name}}/python3_virtualenv_sources/requirements-to-freeze.txt
Labels: Status: Review Needed

#106 Mv conf monitor mfcom
  adm/Makefile
  adm/conf_monitor.py
  adm/mfserv_conf_monitor.py
  config/circus.ini.custom
Labels: Merge Now, Status: Review Needed

#109 feat: we can deactivate the nginx startup
  adm/mfserv_conf_monitor.py
  adm/mfxxx.status.custom
  config/circus.ini.custom
  config/config.ini
Labels: Status: Review Needed

#112 feat: provide an easy way for a plugin to listen to an extra route
  adm/Makefile
  adm/__make_nginx_conf
  adm/_plugins.is_dangerous
  adm/templates/plugins/default/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/django/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/empty/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/node/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/static/{{cookiecutter.name}}/config.ini
Labels: Merge Now, Status: Review Needed

#113 [WIP] feat: execute integration tests directly from mfserv module
  .drone.yml
  integration_tests/0001_test_mfserv_operational/test_mfserv_operational.sh
  integration_tests/0002_python3_plugin/_test.sh
  integration_tests/0002_python3_plugin/foobar/config.ini
  integration_tests/0002_python3_plugin/test.sh
  run_integration_tests.sh
Labels: Status: Pending
