Repository metwork-framework/mfserv, pull requests merged in 2019-12, with the labels that each got.

#287 fix: important fix about max_age feature
  adm/Makefile
  adm/_make_circus_conf
  adm/signal_wrapper.py
  config/socket_updown.lua
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#290 build: refactor nodejs backend to use signal_wrapper.py
  adm/_make_circus_conf
  adm/templates/plugins/node/{{cookiecutter.name}}/package.json
  adm/templates/plugins/node/{{cookiecutter.name}}/{{cookiecutter.name}}/server.js
  layers/layer1_nodejs/0500_metwork_tools/metwork-tools/index.js
  layers/layer1_nodejs/0500_metwork_tools/package-lock.json
  layers/layer1_nodejs/0500_metwork_tools/package.json
Labels: Status: Review Needed

#291 build: config.ini now use a common template
  config/config.ini.custom
Labels: Status: Review Needed

#293 fix max_age disabling feature
  adm/_make_circus_conf
Labels: Status: Revision Needed, backport-to-0.9

#295 fix: change the stop signal with autorestart dev feature
  adm/_make_circus_conf
  adm/signal_wrapper.py
  config/circus.ini.custom
Labels: Merge Now, Status: Revision Needed, backport-to-0.9
