Repository metwork-framework/mfserv, pull requests merged in 2019-06, with the labels that each got.

#182 build: remove useless line (I think), because [app_main] is defined in
  adm/templates/plugins/static/{{cookiecutter.name}}/config.ini
Labels: Status: Revision Needed

#185 Nginxconf
  adm/_make_nginx_conf
  config/nginx.conf
Labels: Status: Review Needed, backport-to-0.7

#188 Misc3
  adm/__make_nginx_conf
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/mediation/{{cookiecutter.name}}/main/application.py
  config/nginx.conf
Labels: Status: Review Needed, backport-to-0.7

#189 Misc4
  adm/__make_nginx_conf
  adm/templates/plugins/_common/config.ini
  config/nginx.conf
Labels: Status: Review Needed, backport-to-0.7

#192 feat: add a new configuration key (for extending nginx conf)
  adm/__make_nginx_conf
  adm/templates/plugins/_common/config.ini
  config/nginx.conf
Labels: Merge Now, Status: Revision Needed

#193 docs: Update MFSERV documentation
  .gitignore
  doc/Makefile
  doc/_images/overall_architecture.svg
  doc/changelogs.tmpl
  doc/conf.py
  doc/index.rst
  doc/mfserv_create_plugins.md
  doc/mfserv_intro.md
  doc/mfserv_load_env.md
  doc/mfserv_tuning_monitoring.md
  doc/src/overall_architecture.graphml
  layers/layer1_python2/0550_bjoern/Makefile.mk
  layers/layer1_python3/0550_bjoern/Makefile.mk
Labels: Status: Review Needed

#196 feat: add template "flask"
  adm/templates/plugins/flask/cookiecutter.json
  adm/templates/plugins/flask/{{cookiecutter.name}}/.autorestart_excludes
  adm/templates/plugins/flask/{{cookiecutter.name}}/.autorestart_includes
  adm/templates/plugins/flask/{{cookiecutter.name}}/.gitignore
  adm/templates/plugins/flask/{{cookiecutter.name}}/.layerapi2_dependencies
  adm/templates/plugins/flask/{{cookiecutter.name}}/.layerapi2_extra_env
  adm/templates/plugins/flask/{{cookiecutter.name}}/.layerapi2_label
  adm/templates/plugins/flask/{{cookiecutter.name}}/Makefile
  adm/templates/plugins/flask/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/__init__.py
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/templates/page_not_found.html
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/templates/template_jinja_examples/index.html
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/templates/template_urlparse/index.html
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/wsgi.py
  adm/templates/plugins/flask/{{cookiecutter.name}}/python3_virtualenv_sources/requirements-to-freeze.txt
  adm/templates/plugins/flask/{{cookiecutter.name}}/python3_virtualenv_sources/requirements3.txt
  integration_tests/0012_flask_plugin/.gitignore
  integration_tests/0012_flask_plugin/test.py
Labels: Status: Review Needed

#197 fix: add the missing line for numprocesses
  config/circus.ini.custom
Labels: Status: Review Needed, backport-to-0.7

#199 Experimental
  bootstrap.sh
Labels: Merge Now, Status: Review Needed

#200 Misc5
  adm/Makefile
  adm/__make_nginx_conf
  adm/_check_circus_conf
  adm/_check_nginx_conf
  adm/_make_circus_conf
  adm/_make_nginx_conf
  adm/_plugins.postinstall
  adm/mfxxx.start.custom
  adm/mfxxx.status.custom
  config/circus.ini.custom
  config/nginx.conf
Labels: Status: Review Needed

#202 feat: add a healthcheck endpoint
  adm/__make_nginx_conf
  config/Makefile
  config/health.lua
  config/nginx.conf
Labels: Status: Review Needed, backport-to-0.7

#201 Flask plugin doc and test update
  adm/templates/plugins/flask/{{cookiecutter.name}}/main/wsgi.py
  integration_tests/0012_flask_plugin/test.py
Labels: Merge Now, Status: Review Needed

#204 doc: correct first sentence and one repetition
  doc/mfserv_intro.md
Labels: Merge Now, Status: Review Needed

#205 feat: add some smart start/stop options and features
  adm/mfxxx.status.custom
  adm/mfxxx.stop.custom
  config/circus.ini.custom
  config/config.ini
  config/nginx.conf
Labels: Merge Now, Status: Review Needed, backport-to-0.7
