Repository metwork-framework/mfserv, pull requests merged in 2019-10, with the labels that each got.

#252 fix: fix circus generation test
  adm/_make_circus_conf
Labels: Merge Now, Status: Review Needed

#254 feat: build mfserv without mfcom (mfcom layers are now included in mf…
  .drone.yml
  .gitignore
  .layerapi2_dependencies
  adm/Makefile
  adm/__make_nginx_conf
  adm/_plugins.postinstall
  adm/mfxxx.status.custom
  adm/templates/plugins/_common/Makefile
  adm/templates/plugins/flask/{{cookiecutter.name}}/Makefile
  bootstrap.sh
  config/Makefile
  doc/mfserv_deploy_plugin.md
  doc/mfserv_quick_start.md
  layer_custom.md
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python2/0500_extra_python_packages/Makefile.mk
  layers/layer1_python3/.layerapi2_dependencies
  layers/layer1_python3/0500_extra_python_packages/Makefile.mk
  layers/layer9_default/.layerapi2_dependencies
  plugins/welcome/Makefile
Labels: Merge Now, Status: Revision Needed

#257 feat: add nodejs mflog lib
  layers/layer1_nodejs/.layerapi2_extra_env
  layers/layer1_nodejs/0500_metwork_tools/Makefile.mk
  layers/layer1_nodejs/0500_metwork_tools/metwork-tools/index.js
  layers/layer1_nodejs/0500_metwork_tools/package-lock.json
  layers/layer1_nodejs/0500_metwork_tools/package.json
Labels: Status: Review Needed, backport-to-0.8

#258 feat: infinite max_retry for circus
  config/circus.ini.custom
Labels: Status: Review Needed

#260 feat: add an option for x_forwarded headers
  config/config.ini
  config/nginx.conf
Labels: Status: Review Needed, backport-to-0.8

#261 feat: add a warning if nginx/port is < 1024
  adm/_check_nginx_conf
  config/config.ini
Labels: Status: Review Needed

#267 feat: better default dependencies
  adm/templates/plugins/default/{{cookiecutter.name}}/.layerapi2_dependencies
  adm/templates/plugins/django/{{cookiecutter.name}}/.layerapi2_dependencies
  adm/templates/plugins/empty/{{cookiecutter.name}}/.layerapi2_dependencies
  adm/templates/plugins/flask/{{cookiecutter.name}}/.layerapi2_dependencies
  adm/templates/plugins/mediation/{{cookiecutter.name}}/.layerapi2_dependencies
  adm/templates/plugins/node/{{cookiecutter.name}}/.layerapi2_dependencies
  adm/templates/plugins/static/{{cookiecutter.name}}/.layerapi2_dependencies
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#271 feat: little improvment in socket up/down feature
  config/socket_updown.lua
Labels: Merge Now, Status: Review Needed, backport-to-0.9
