Repository metwork-framework/mfserv, pull requests merged in 2020-07, with the labels that each got.

#359 feat: fix details in documentation (including comment lines in config…
  adm/templates/plugins/_common/config.ini
  config/config.ini.custom
  docs/950-old_docs/.pages
Labels: backport-to-1.0

#362 build: doc update
  adm/templates/plugins/node/README.md
  adm/templates/plugins/node_noweb/README.md
  adm/templates/plugins/openresty/README.md
  adm/templates/plugins/python3_tornado/README.md
  adm/templates/plugins/static/README.md
  docs/.gitignore
Labels: Merge Now

#361 build: remove deprecated nodejs code
  layers/layer1_nodejs/0500_metwork_tools/metwork-tools/index.js
Labels: Merge Now, backport-to-1.0

#365 Update README.md
  adm/templates/plugins/openresty/README.md
Labels: Merge Now, backport-to-1.0

#366 build: new READMEs
  adm/templates/plugins/python2_flask/README.md
  adm/templates/plugins/python2_noweb/README.md
  adm/templates/plugins/python3_flask/README.md
  adm/templates/plugins/python3_noweb/README.md
Labels: Merge Now

#367 build: timeouts improvments
  adm/plugins.py
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/python2_flask/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/python3_django/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/python3_flask/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/python3_raw_wsgi/{{cookiecutter.name}}/config.ini
Labels: Merge Now

#369 build: doc update
  .metwork-framework/README.md
  adm/templates/plugins/python2_raw_wsgi/README.md
  adm/templates/plugins/python3_aiohttp/README.md
  adm/templates/plugins/python3_raw_wsgi/README.md
  docs/010-whatis.md
  docs/020-quickstart.md
  docs/images/quickstart_screenshot.png
Labels: Status: Merge Now, Status: Review Needed, Type: Enhancement

#370 build: some readme update
  adm/templates/plugins/_common/crontab
  adm/templates/plugins/python3_django/README.md
  adm/templates/plugins/python3_raw_asgi/README.md
Labels: Status: Merge Now, Status: Review Needed
