Repository metwork-framework/mfserv, pull requests merged in 2020-09, with the labels that each got.

#380 build: fix documentation detail
  adm/templates/plugins/node_noweb/README.md
  adm/templates/plugins/python2_flask/README.md
  adm/templates/plugins/python2_raw_wsgi/README.md
  adm/templates/plugins/python3_django/README.md
  adm/templates/plugins/python3_flask/README.md
  adm/templates/plugins/python3_raw_asgi/README.md
  adm/templates/plugins/python3_raw_wsgi/README.md
  adm/templates/plugins/static/README.md
  docs/010-whatis.md
Labels: Status: Review Needed

#389 feat: load the pythonX_scientific_core layer by default in plugins (if the layer is installed)
  adm/templates/plugins/_common/python2_layerapi2_dependencies
Labels: Status: Revision Needed, backport-to-1.0

#393 feat: add a configuration option to open the endpoint /uuid to other …
  config/config.ini.custom
  config/nginx.conf
Labels: Status: Review Needed, backport-to-0.9, backport-to-1.0

#401 docs: update old docs
  docs/950-old_docs/010-mfserv_intro.md
  docs/950-old_docs/020-mfserv_load_env.md
  docs/950-old_docs/030-mfserv_quick_start.md
  docs/950-old_docs/040-mfserv_create_plugins.md
  docs/950-old_docs/050-mfserv_debug_plugin.md
  docs/950-old_docs/060-mfserv_deploy_plugin.md
  docs/950-old_docs/070-mfserv_tutorials.md
  docs/950-old_docs/080-mfserv_tuning_monitoring.md
  docs/950-old_docs/090-mfserv_miscellaneous.md
  docs/950-old_docs/100-mfserv_log.md
Labels: Status: Review Needed
