Repository metwork-framework/mfserv, pull requests merged in 2020-01, with the labels that each got.

#297 fix: change the stop signal with autorestart dev feature
  adm/_make_circus_conf
  adm/signal_wrapper.py
  config/circus.ini.custom
Labels: Merge Now, Status: Review Needed

#299 [WIP] feat: log refactoring
  adm/__make_nginx_conf
  adm/_make_circus_conf
  adm/plugins_common.py
  adm/plugins_deprecated.py
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/static/{{cookiecutter.name}}/config.ini
  config/Makefile
  config/circus.ini.custom
  config/config.ini.custom
  config/nginx.conf
  config/redis_plugin_xxx.conf
Labels: Merge Now, Status: Revision Needed

#300 build: some fixes about recent log refactoring
  adm/__make_nginx_conf
  config/nginx.conf
  layers/layer1_nodejs/.layerapi2_dependencies
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python3/.layerapi2_dependencies
Labels: Merge Now, Status: Review Needed

#303 build: fix crontabs
  adm/templates/plugins/_common/crontab
Labels: Merge Now, Status: Revision Needed

#305 fix: fix signal_wrapper in python2
  adm/signal_wrapper.py
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#307 build: configparser_extend drop
  adm/__make_nginx_conf
  adm/_make_circus_conf
  adm/_plugins.is_dangerous
Labels: Merge Now, Status: Revision Needed

#310 build: fix build
  adm/__make_nginx_conf
Labels: Merge Now, Status: Review Needed

#309 feat: port of mflog changes about syslog to node
  layers/layer1_nodejs/0500_metwork_tools/Makefile.mk
  layers/layer1_nodejs/0500_metwork_tools/metwork-tools/index.js
  layers/layer1_nodejs/0500_metwork_tools/package-lock.json
  layers/layer1_nodejs/0500_metwork_tools/package.json
Labels: Status: Review Needed

#311 fix: fix a compatibility issue with old static plugins
  adm/__make_nginx_conf
  config/nginx.conf
  integration_tests/0100_issue301/.gitignore
  integration_tests/0100_issue301/mystatic-0.0.1-1.metwork.mfserv.plugin
  integration_tests/0100_issue301/test.py
Labels: Merge Now, Status: Review Needed

#312 build: some changes for issue269
  adm/mfserv_conf_monitor.py
  adm/profile.custom
  config/circus.ini.custom
Labels: Merge Now, Status: Review Needed

#313 fix: remove rlimit_core (because of `ulimit -c 0` in mfext)
  adm/templates/plugins/_common/config.ini
  config/circus.ini.custom
  doc/mfserv_tuning_monitoring.md
Labels: Status: Review Needed
