Repository metwork-framework/mfserv, pull requests merged in 2020-05, with the labels that each got.

#334 feat: remove all references to MFCOM or mfcom, including backward com…
  adm/templates/plugins/_common/config.ini
  config/config.ini.custom
Labels: Status: Revision Needed

#330 [WIP] mfextaddon_python2
  .metwork-framework/components.md
  integration_tests/0003_python_raw_wsgi/test.py
  integration_tests/0004_noweb/test.py
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python2/.layerapi2_label
  layers/layer1_python2/0550_bjoern/Makefile
  layers/layer1_python2/0550_bjoern/Makefile.mk
  layers/layer1_python2/0550_bjoern/sources
  layers/layer1_python2/Makefile
  layers/layer1_python2/layer_custom.md
  layers/layer1_python3/0550_bjoern/Makefile
  layers/layer1_python3/0550_bjoern/Makefile.mk
  layers/layer1_python3/0550_bjoern/sources
Labels: Merge Now, Status: Review Needed

#337 Fix misc
  adm/plugins.py
  adm/templates/plugins/_common/python2_layerapi2_dependencies
Labels: Merge Now, Status: Revision Needed

#338 feat: allow binary packages by default (for plugins)
  adm/templates/plugins/_common/python2_layerapi2_dependencies
  adm/templates/plugins/_common/python2_virtualenv_sources/allow_binary_packages
  adm/templates/plugins/_common/python3_virtualenv_sources/allow_binary_packages
  adm/templates/plugins/python2_flask/{{cookiecutter.name}}/python2_virtualenv_sources/allow_binary_packages
  adm/templates/plugins/python3_django/{{cookiecutter.name}}/python3_virtualenv_sources/allow_binary_packages
  adm/templates/plugins/python3_flask/{{cookiecutter.name}}/python3_virtualenv_sources/allow_binary_packages
  adm/templates/plugins/python3_raw_asgi/{{cookiecutter.name}}/python3_virtualenv_sources/allow_binary_packages
  adm/templates/plugins/python3_tornado/{{cookiecutter.name}}/python3_virtualenv_sources/allow_binary_packages
Labels: Merge Now, Status: Review Needed

#340 fix: fix timeout value when <=0
  adm/plugins.py
Labels: Merge Now, backport-to-1.0
