Repository metwork-framework/mfserv, pull requests merged in 2020-10, with the labels that each got.

#404 build: add .configuration_cache in plugins default .gitignore
  adm/templates/plugins/_common/.gitignore
Labels: Status: Review Needed, backport-to-1.0

#407 docs: update mfserv documentation and remove old docs
  adm/templates/plugins/node/README.md
  adm/templates/plugins/node/{{cookiecutter.name}}/{{cookiecutter.name}}/server.js
  adm/templates/plugins/node_noweb/README.md
  adm/templates/plugins/python2_flask/README.md
  adm/templates/plugins/python3_aiohttp/README.md
  adm/templates/plugins/python3_aiohttp/{{cookiecutter.name}}/main/application.py
  adm/templates/plugins/python3_django/README.md
  adm/templates/plugins/python3_django/{{cookiecutter.name}}/postinstall
  adm/templates/plugins/python3_flask/README.md
  docs/360-mfserv_debug_plugin.md
  docs/870-tutorials/.pages
  docs/870-tutorials/010-node_plugin.md
  docs/870-tutorials/020-python2_flask_plugin.md
  docs/870-tutorials/030_python3_aiohttp_plugin.md
  docs/870-tutorials/040_python3_django_plugin.md
  docs/870-tutorials/050_python3_flask_plugin.md
  docs/950-old_docs/.pages
  docs/950-old_docs/mfserv_create_plugins.md
  docs/950-old_docs/mfserv_debug_plugin.md
  docs/950-old_docs/mfserv_deploy_plugin.md
  docs/950-old_docs/mfserv_intro.md
  docs/950-old_docs/mfserv_load_env.md
  docs/950-old_docs/mfserv_log.md
  docs/950-old_docs/mfserv_miscellaneous.md
  docs/950-old_docs/mfserv_quick_start.md
  docs/950-old_docs/mfserv_tuning_monitoring.md
  docs/950-old_docs/mfserv_tutorials.md
  docs/950-old_docs/overall_architecture.svg
  docs/images/mfserv_debug_interactive.jpg
  docs/images/mfserv_django_tuto_admin_site.jpg
Labels: Status: Review Needed, backport-to-1.0

#411 fix: don't prevent nginx to bind <1024 port (with setcap)
  adm/_check_nginx_conf
Labels: Status: Merge Now, Status: Review Needed, backport-to-0.9, backport-to-1.0

#414 build: force a CI event
  README.md
Labels: Status: Merge Now

#415 docs: add some note about #411 change
  config/config.ini.custom
Labels: Status: Merge Now, backport-to-0.9, backport-to-1.0

#418 feat: backport of https support and <1024 port binding (from 1.0 branch)
  adm/_check_nginx_conf
  adm/_make_nginx_conf
  config/config.ini
  config/nginx.conf
Labels: Status: Merge Now, Status: Review Needed

#425 fix: bug with static files when extra_route is set to /
  config/nginx.conf
Labels: Status: Merge Now, Status: Review Needed

#424 fix: bug with static files when extra_route is set to /
  config/nginx.conf
Labels: Status: Merge Now, Status: Review Needed, backport-to-1.0
