Repository metwork-framework/mfserv, pull requests merged in 2020-02, with the labels that each got.

#314 build: pythonX_misc layer drop
  layer_custom.md
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python3/.layerapi2_dependencies
  layers/layer1_python3/0500_extra_python_packages/Makefile.mk
Labels: Merge Now, Status: Revision Needed

#316 build: pythonX_misc layer drop
  layers/layer1_python2/.layerapi2_dependencies
  plugins/welcome/.layerapi2_dependencies
Labels: Merge Now, Status: Revision Needed

#317 Drop python x misc
  .metwork-framework/components.md
  layers/layer1_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Revision Needed

#318 Drop python x misc
  layers/layer1_python2/.layerapi2_dependencies
  layers/layer1_python3/.layerapi2_dependencies
Labels: Status: Review Needed

#319 build: preliminary changes for metwork-framework/resources#39
  adm/__make_nginx_conf
  adm/_check_circus_conf
  adm/_check_nginx_conf
  adm/_make_circus_conf
  adm/_plugins.is_dangerous
  adm/plugins.hotswap
Labels: Status: Review Needed

#320 feat: remove absolute log paths from log_proxy usages (LOGPROXY_LOG_D…
  adm/templates/plugins/_common/crontab
  config/circus.ini.custom
  doc/mfserv_miscellaneous.md
Labels: Merge Now, Status: Review Needed

#323 feat: https/ssl support for nginx in mfserv
  adm/_make_nginx_conf
  config/config.ini.custom
  config/nginx.conf
Labels: Status: Review Needed
