Repository metwork-framework/mfserv, pull requests merged in 2021-05, with the labels that each got.

#493 build: update workflows (from common files)
  .github/workflows/build.sh
  .github/workflows/ci.yml
  .github/workflows/createrepo.sh
Labels: Status: Merge Now, Status: Review Needed

#495 fix: fix a plugin context issue
  adm/plugins.py
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#498 build: update ci.yml (add step mageia repo)
  .github/workflows/ci.yml
Labels: Status: Merge Now

#499 fix: we can use from_json jinja2 extension in nginx configuration files
  adm/plugins.py
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#502 build: CI under github actions
  .drone.yml
  .github/workflows/bootstrap_ci.sh
  .github/workflows/build.sh
  .github/workflows/ci.yml
  .github/workflows/createrepo.sh
  .github/workflows/integration_tests.sh
  .github/workflows/set_variables.sh
Labels: Status: Merge Now
