Repository metwork-framework/mfserv, pull requests merged in 2021-04, with the labels that each got.

#484 fix: fix nginx root usage in some CI corner cases
  config/nginx.conf
Labels: Status: Merge Now, Status: Review Needed, backport-to-0.9, backport-to-1.0

#487 fix: fix a complex issue about nginx var caching
  config/nginx.conf
Labels: Status: Merge Now, Status: Review Needed

#488 build: Update nginx.conf
  config/nginx.conf
Labels: Status: Merge Now

#491 docs: correct spelling of 040_python3_django_plugin.md
  docs/870-tutorials/040_python3_django_plugin.md
Labels: Status: Review Needed

#492 build: sync common files from github_organization_management repository
  .github/workflows/set_variables.sh
Labels: Status: Merge Now
