Repository metwork-framework/mfserv, pull requests merged in 2023-10, with the labels that each got.

#606 feat: fix link to rpms repository in installation guide
  docs/100-installation_guide.md
Labels: Status: Merge Now

#608 fix: .release_ignore instead of .releaseignore in common.mk (closes #…
  plugins/common.mk
Labels: Status: Review Needed, backport-to-2.1

#610 build: rename .release_ignore into .releaseignore for welcome plugin
  plugins/welcome/.gitignore
Labels: Status: Review Needed
