Repository metwork-framework/mfserv, pull requests merged in 2024-10, with the labels that each got.

#634 fix: fix vulnerabilites in django (CVE-2024-45231 and CVE-2024-45230)
  adm/templates/plugins/python3_django/{{cookiecutter.name}}/python3_virtualenv_sources/requirements-to-freeze.txt
Labels: Status: Merge Now, backport-to-2.2

#637 fix: enable the access log for the healthcheck endpoint (closes #1958)
  config/config.ini.custom
  config/nginx.conf
Labels: Status: Review Needed, backport-to-2.2

#639 build: use checkout@v4
  .github/workflows/ci.yml
Labels: Status: Merge Now

#640 build: fix previous commit
  config/nginx.conf
Labels: Status: Review Needed
