Repository metwork-framework/mfserv, pull requests merged in 2025-03, with the labels that each got.

#649 feat: plugin PHP template
  adm/Makefile
  adm/php_wrapper
  adm/plugins.py
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/php/README.md
  adm/templates/plugins/php/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/php/{{cookiecutter.name}}/main/index.php
  adm/templates/plugins/php/{{cookiecutter.name}}/php_extra_server.conf
  config/nginx.conf
Labels: Status: Review Needed

#650 feat: bump django to 5.0.13 in template django to fix CVE-2025-26699
  adm/templates/plugins/python3_django/{{cookiecutter.name}}/python3_virtualenv_sources/requirements-to-freeze.txt
Labels: Status: Merge Now

#651 fix: bump django to 4.2.20 in template django to fix CVE-2025-26699
  adm/templates/plugins/python3_django/{{cookiecutter.name}}/python3_virtualenv_sources/requirements-to-freeze.txt
Labels: Status: Merge Now

#652 build: change default page for template php
  adm/templates/plugins/php/{{cookiecutter.name}}/main/index.php
Labels: Status: Review Needed

#655 build: fix errors in extra_nginx_conf, integration test : don't need index.php anymore
  adm/templates/plugins/_common/config.ini
  adm/templates/plugins/php/{{cookiecutter.name}}/config.ini
  adm/templates/plugins/php/{{cookiecutter.name}}/extra_nginx_conf_main.conf
  integration_tests/0013_php_plugin/test.py
Labels: Status: Review Needed, Status: Merge Now

#656 build: remove renamed file extra_nginx_conf
  adm/templates/plugins/php/{{cookiecutter.name}}/extra_nginx_conf_main
Labels: Status: Review Needed
